name: Build and push OCI image

on:
  schedule:
    - cron: '5 3 * * *'  # UTC
  push:
    branches:
      - master
      - '[0-9].[0-9]'
      - '[0-9].[0-9]p[0-9]'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=openbgpd/openbgpd
          QUAY_IMAGE=quay.io/openbgpd/openbgpd
          TAG=noop
          PORTABLE_COMMIT=noop
          if [ "${{ github.event_name }}" = "schedule" ]; then
            TAG=edge
            PORTABLE_COMMIT=master
          elif [[ ${GITHUB_REF} == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            PORTABLE_COMMIT=${TAG}
          elif [[ ${GITHUB_REF} == refs/heads/* ]]; then
            TAG=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            PORTABLE_COMMIT=${TAG}
            if [ "${{ github.event.repository.default_branch }}" = "${TAG}" ]; then
              TAG=edge
              PORTABLE_COMMIT=master
            fi
          fi
          TAGS="${DOCKER_IMAGE}:${TAG},${QUAY_IMAGE}:${TAG}"
          if [[ $TAG =~ ^[0-9]{1,3}\.[0-9]{1,3}(p[0-9]{1,3})*$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest,${QUAY_IMAGE}:latest"
            BUILD_ARGS="VERSION=${TAG}"
          else
            BUILD_ARGS="PORTABLE_COMMIT=${PORTABLE_COMMIT}"
          fi
          echo ::set-output name=version::${TAG}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=args::${BUILD_ARGS}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Quay Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Multi-arch Dockerfile
        run: sed -e 's/^\(FROM\) \(alpine:.*\)/ARG ARCH=\n\1 ${ARCH}\2/' -i Dockerfile
      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          build-args: ${{ steps.prep.outputs.args }}
          labels: |
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.label-schema.version=${{ steps.prep.outputs.version }}
            org.label-schema.build-date=${{ steps.prep.outputs.created }}
            org.label-schema.vcs-ref=${{ github.sha }}
